//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PackagingType = newPackagingTypeTable("public", "packaging_type", "")

type packagingTypeTable struct {
	postgres.Table

	// Columns
	ID   postgres.ColumnInteger
	Name postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PackagingTypeTable struct {
	packagingTypeTable

	EXCLUDED packagingTypeTable
}

// AS creates new PackagingTypeTable with assigned alias
func (a PackagingTypeTable) AS(alias string) *PackagingTypeTable {
	return newPackagingTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PackagingTypeTable with assigned schema name
func (a PackagingTypeTable) FromSchema(schemaName string) *PackagingTypeTable {
	return newPackagingTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PackagingTypeTable with assigned table prefix
func (a PackagingTypeTable) WithPrefix(prefix string) *PackagingTypeTable {
	return newPackagingTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PackagingTypeTable with assigned table suffix
func (a PackagingTypeTable) WithSuffix(suffix string) *PackagingTypeTable {
	return newPackagingTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPackagingTypeTable(schemaName, tableName, alias string) *PackagingTypeTable {
	return &PackagingTypeTable{
		packagingTypeTable: newPackagingTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newPackagingTypeTableImpl("", "excluded", ""),
	}
}

func newPackagingTypeTableImpl(schemaName, tableName, alias string) packagingTypeTable {
	var (
		IDColumn       = postgres.IntegerColumn("id")
		NameColumn     = postgres.StringColumn("name")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn}
		mutableColumns = postgres.ColumnList{NameColumn}
	)

	return packagingTypeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
