//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var DefectsType = newDefectsTypeTable("public", "defects_type", "")

type defectsTypeTable struct {
	postgres.Table

	// Columns
	ID    postgres.ColumnInteger
	Name  postgres.ColumnString
	Value postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type DefectsTypeTable struct {
	defectsTypeTable

	EXCLUDED defectsTypeTable
}

// AS creates new DefectsTypeTable with assigned alias
func (a DefectsTypeTable) AS(alias string) *DefectsTypeTable {
	return newDefectsTypeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DefectsTypeTable with assigned schema name
func (a DefectsTypeTable) FromSchema(schemaName string) *DefectsTypeTable {
	return newDefectsTypeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DefectsTypeTable with assigned table prefix
func (a DefectsTypeTable) WithPrefix(prefix string) *DefectsTypeTable {
	return newDefectsTypeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DefectsTypeTable with assigned table suffix
func (a DefectsTypeTable) WithSuffix(suffix string) *DefectsTypeTable {
	return newDefectsTypeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDefectsTypeTable(schemaName, tableName, alias string) *DefectsTypeTable {
	return &DefectsTypeTable{
		defectsTypeTable: newDefectsTypeTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newDefectsTypeTableImpl("", "excluded", ""),
	}
}

func newDefectsTypeTableImpl(schemaName, tableName, alias string) defectsTypeTable {
	var (
		IDColumn       = postgres.IntegerColumn("id")
		NameColumn     = postgres.StringColumn("name")
		ValueColumn    = postgres.StringColumn("value")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn, ValueColumn}
		mutableColumns = postgres.ColumnList{NameColumn, ValueColumn}
	)

	return defectsTypeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:    IDColumn,
		Name:  NameColumn,
		Value: ValueColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
